<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.6.1.0</Version>
    <Authors>Los</Authors>
    <PackageProjectUrl>https://github.com/Elio0825/CrescentAuto</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DalamudLibPath Condition="'$(DALAMUD_HOME)' == '' and Exists('$(APPDATA)\XIVLauncherCN\addon\Hooks\dev\Dalamud.dll')">$(APPDATA)\XIVLauncherCN\addon\Hooks\dev\</DalamudLibPath>
    <AssemblySearchPaths>$(AssemblySearchPaths);$(DalamudLibPath)</AssemblySearchPaths>
  </PropertyGroup>
</Project>
